### ISSUE TITLE
Government Support

### ISSUE THREAD

**Issue by SparklyMalo** [azureautomation/azure-automation-ise-addon#104]
Is there a way to set the Service Endpoint with the Azure Government Cloud?

**Comment by eamonoreilly** [comment]
Unfortunately, the endpoints are not currently configurable. I'll have a look to see what endpoints should be exposed in the config file (they are currently in the constants.cs file) and see if I can move them in there. I might need some help testing as I don't have access to a government cloud but I might be able to get one in the team that I can use.
Thanks for the request,
Eamon

**Comment by Commochief** [comment]
Hope this might help. If you need someone to test feel free to reach out and I can try it.

Here is the command I run to connect to my AzureUSGov subscription.

$EnvName = "AzureGovernmentCloud"
$PubSettingsURL = "https://manage.windowsazure.us/publishsettings/index"
$ServiceEndPoint = "https://management.core.usgovcloudapi.net/"
$ManagementPortalURL = "https://manage.windowsazure.us/"
$ADEndpoint = "https://login.windows.net/"
$ADSvcEndpointResId = "https://management.core.usgovcloudapi.net/"
$StorageEndpoint = "core.usgovcloudapi.net"

Add-AzureEnvironment -Name $EnvName `
                     -PublishSettingsFileUrl $PubSettingsURL`
                     -ServiceEndpoint $ServiceEndPoint  `
                     -ManagementPortalUrl $ManagementPortalURL`
                     -ActiveDirectoryEndpoint $ADEndpoint `
                     -ActiveDirectoryServiceEndpointResourceId $ADSvcEndpointResId`
                     -StorageEndpoint $StorageEndpoint

**Comment by devkeydet** [comment]
Any news on when this might be supported?

**Comment by Commochief** [comment]
This is already fixed. They added a builtin environment called AzureUSGovernment.

PS C:\Program Files\SAPIEN Technologies, Inc\PowerShell Studio 2017> Get-AzureEnvironment AzureUSGovernment        
                                                                                                                   
                                                                                                                   
Name                                     : AzureUSGovernment                                                       
EnableAdfsAuthentication                 : False                                                                   
ActiveDirectoryServiceEndpointResourceId : https://management.core.usgovcloudapi.net/                              
AdTenant                                 :                                                                         
GalleryUrl                               : https://gallery.usgovcloudapi.net/                                      
ManagementPortalUrl                      : https://manage.windowsazure.us                                          
ServiceManagementUrl                     : https://management.core.usgovcloudapi.net/                              
PublishSettingsFileUrl                   : https://manage.windowsazure.us/publishsettings/index                    
ResourceManagerUrl                       : https://management.usgovcloudapi.net/                                   
SqlDatabaseDnsSuffix                     : .database.usgovcloudapi.net                                             
StorageEndpointSuffix                    : core.usgovcloudapi.net                                                  
ActiveDirectoryAuthority                 : https://login-us.microsoftonline.com/                                   
GraphUrl                                 : https://graph.windows.net/                                              
TrafficManagerDnsSuffix                  : usgovtrafficmanager.net                                                 
AzureKeyVaultDnsSuffix                   : vault.usgovcloudapi.net                                                 
AzureKeyVaultServiceEndpointResourceId   : https://vault.usgovcloudapi.net

**Comment by devkeydet** [comment]
Right, but how do you use it with the addon?

**Comment by eamonoreilly** [comment]
You can't use with the add-on right now. I would basically have to add a drop down to select the environment and then change the URLs to point to the above list instead of the default public Azure ones. I don't have an eta for this at the moment but I'll do some investigation.
Thanks,
Eamon

**Comment by hbaxeric** [comment]
I'm wondering if there is a roadmap for adding the Gov integration.  I'm a heavy user of this add-on, and much to my dismay my organization has switched from commercial to gov cloud.

**Comment by eamonoreilly** [comment]
US Government support is now available. It will show up on the next release on the PowerShell gallery or you can build from source if you want to try it out before then.
Thanks,
Eamon
