### ISSUE TITLE
Add support for Azure Automation DSC

### ISSUE THREAD

**Issue by pcgeek86** [azureautomation/azure-automation-ise-addon#106]
This add-on is ridiculously useful for Azure Automation Runbooks! However, for future enhancement, it would be very cool if we could get support for Azure Automation Desired State Configuration (DSC).

The proposed feature set would include:
- Upload / sync PowerShell DSC documents between the local system and Azure Automation Accounts
- Invoke compilation jobs with Configuration Data
- Invoke compilation jobs without Configuration Data
- Insert Azure Automation assets into a DSC configuration document while authoring locally
- Generate meta-configurations for onboarding non-Azure Virtual (and Physical) Machines
- Onboard Azure Virtual Machines automatically using the Azure VM DSC Extension

Cheers,
**Trevor Sullivan**
Microsoft MVP: PowerShell
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by JAL9302** [comment]
Agree on most of this:
- Upload / sync PowerShell DSC documents between the local system and Azure Automation Accounts
- Invoke compilation jobs with/without Configuration Data
- Insert Azure Automation assets into a DSC configuration document while authoring locally (_this one should already be possible_)

For these ones, these aren't authoring / testing scenarios, so not sure it fits with the current scope of the ISE add on:
- Generate meta-configurations for onboarding non-Azure Virtual (and Physical) Machines
- Onboard Azure Virtual Machines automatically using the Azure VM DSC Extension

**Comment by pcgeek86** [comment]
Thanks for the feedback, Joe. Agreed on all points. Just thought that onboarding for testing might be faster using the add-on, but agree that it's mostly a production scenario.

**Comment by eamonoreilly** [comment]
Closing this out with DSC now available in the Add-On. 
Thanks,
Eamon
