### ISSUE TITLE
AzureAutomationAuthoringToolkit: Warning - Local value for  PSCredential asset 'CredentialAssetName' not found.

### ISSUE THREAD

**Issue by LouisGomme** [azureautomation/azure-automation-ise-addon#111]
Hello,

I have been using Azure Automation in Azure Runbook, and in PowerShell ISE. The script I use to login on ARM resources works fine in my PowerShell ISE, however the same script in an Azure Runbook returns an error.

Here is the code I use in the Azure Runbook:

```
#The name of the Automation Credential Asset this runbook will use to authenticate to Azure.
    $CredentialAssetName = "louisautomation2"

    #Get the credential with the above name from the Automation Asset store
    $Cred = Get-AutomationPSCredential -Name $CredentialAssetName
    if(!$Cred) {
        Throw "Louis: Could not find an Automation Credential Asset named '${CredentialAssetName}'. Make sure you have created one in this Automation Account."
    }

    #Connect to your Azure Account (RM)
    $Account = Add-AzureRMAccount -Credential $Cred
    if(!$Account) {
        Throw "Could not authenticate to Azure using the credential asset '${CredentialAssetName}'. Make sure the user name and password are correct."
    }
```

The error I get in the test pane of Azure Automation Runbook when I execute this script is: 
_

> 89abb764-9e1a-4db8-8950-13dc530da954:[localhost]:AzureAutomationAuthoringToolkit: Warning - Local value for PSCredential asset 'louisautomation2' not found.

_

I first had this issue in my PowerShell ISE, but I managed to fix it by using the login feature of the Azure Automation Authoring Toolkit (saving login and password). However, how is it possible to do that in Azure ?

Many thanks !

**Comment by JAL9302** [comment]
Are you running this runbook on a hybrid worker? Or did you import the AzureAutomationAuthoringToolkit module into Azure Automation? Neither of these things is supported.

You can create credential assets in Azure Automation by following the directions here: https://azure.microsoft.com/en-us/documentation/articles/automation-credentials/

**Comment by LouisGomme** [comment]
Thank you for your reply.

I'm not running an hybrid worker (I don't even know what this is to be honest). I've imported the AzureAutomationAuthoringToolkit in my ISE and in my automation account in Azure (in the modules). 

I have created an automation asset in my automation account, which is called "louisautomation2", and login/password are correct. The login 'automation2@lgombeaulive438.onmicrosoft.com' is declared in my AAD as an owner of my subscription.

Then, I want to create a very simple script to display all the VMs in my subscription. Therefore, I use the following code:

```
$myCredential = Get-AutomationPSCredential -Name 'louisautomation2'
$userName = $myCredential.UserName
$securePassword = $myCredential.Password
$password = $myCredential.GetNetworkCredential().Password

$psCred = New-Object System.Management.Automation.PSCredential($userName,$securePassword)

Login-AzureRmAccount -Credential $psCred

$Vms = Get-AzureRmVM
echo $Vms
```

When I run this script in my ISE, it works perfectly and VMs list is displayed.

However, when I execute this script as a runbook in my automation account, it throws erros:

> [localhost]:AzureAutomationAuthoringToolkit: Warning - Local value for 
> PSCredential asset 'louisautomation2' not found.
> 
> You cannot call a method on a null-valued expression.
> At line:19 char:1
> - $password = $myCredential.GetNetworkCredential().Password
> - ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>   - CategoryInfo          : InvalidOperation: (:) [], RuntimeException
>   - FullyQualifiedErrorId : InvokeMethodOnNull
> 
> New-Object : Exception calling ".ctor" with "2" argument(s): "Cannot process argument because the value of argument 
> "userName" is not valid. Change the value of the "userName" argument and run the operation again."
> At line:21 char:11
> - $psCred = New-Object System.Management.Automation.PSCredential($userN ...
> -           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>   - CategoryInfo          : InvalidOperation: (:) [New-Object], MethodInvocationException
>   - FullyQualifiedErrorId : ConstructorInvokedThrowException,Microsoft.PowerShell.Commands.NewObjectCommand
> 
> Add-AzureRmAccount : Cannot bind argument to parameter 'Credential' because it is null.
> At line:23 char:34
> - Login-AzureRmAccount -Credential $psCred
> -                                  ~~~~~~~
>   - CategoryInfo          : InvalidData: (:) [Add-AzureRmAccount], ParameterBindingValidationException
>   - FullyQualifiedErrorId : 
>     ParameterArgumentValidationErrorNullNotAllowed,Microsoft.Azure.Commands.Profile.AddAzureRMAccountCommand
> 
> Get-AzureRmVM : Run Login-AzureRmAccount to login.
> At line:28 char:8
> - $Vms = Get-AzureRmVM
> -        ~~~~~~~~~~~~~
>   - CategoryInfo          : InvalidOperation: (:) [Get-AzureRmVM], PSInvalidOperationException
>   - FullyQualifiedErrorId : InvalidOperation,Microsoft.Azure.Commands.Compute.GetAzureVMCommand

I'm confused with authentication methods in Azure... I'd be glad if you can help :)

Many thanks.

**Comment by JAL9302** [comment]
Hi,

Please remove the AzureAutomationAuthoringToolkit module from your Automation account in Azure, you don't need it there as we already have asset cmdlets built in. Then everything should just work!

**Comment by LouisGomme** [comment]
Thank you @jodoglevy. It solves the issue related to authentication.

Now, I have another issue which is: I don't understand why does the "Get-AzureRMVm" command throw an error after the authentication is done... But that's another story. I created a post [here](https://azure.microsoft.com/en-us/blog/announcing-azure-resource-manager-support-azure-automation-runbooks/).

Thanks again.
