### ISSUE TITLE
Azure Subscription level rights should not be required to use the add-on

### ISSUE THREAD

**Issue by treymorganthd** [azureautomation/azure-automation-ise-addon#112]
I had to grant a non-admin user subscription level rights in order for the azure automation ISE add-on to work.  I was unable to get him up and running with contributor rights on a specific azure automation resource.  I don't see why it is a requirement to grant a user subscription level rights in order to use this add-on.  Seems like a bug or a change request if this is an unknown requirement.

**Comment by JAL9302** [comment]
@eamonoreilly is this because we need to list resource groups and automation accounts?

**Comment by eamonoreilly** [comment]
Yes. If you add the user to the resource group that the automation account belongs to then it will work with just contributor role.
I'll have a look if at having it work just on the automation account and not require the user to have access to the resource group.

**Comment by treymorganthd** [comment]
Good to know.  I will try out the resource group contributor role assignment.  Thanks!

**Comment by eamonoreilly** [comment]
I have made the change to retrieve automation accounts even if the user does not have access to the resource group the automation account is a member of. Closing this out and will be available in the next drop to PowerShell Gallery.
Thanks.

**Comment by treymorganthd** [comment]
Thank you!
