### ISSUE TITLE
ISE Crashes when this add-on is loaded and I close the script

### ISSUE THREAD

**Issue by treymorganthd** [azureautomation/azure-automation-ise-addon#113]
This azure automation add-on seems buggy.  When closing an azure automation script, ISE crashes with this add-on enabled.  The crashes are reproducible and were reported by multiple users here at The Home Depot.  
![ise crash with auzure automation add on](https://cloud.githubusercontent.com/assets/19695323/15726679/d75bf316-2817-11e6-9a9a-59b1b7b4172d.jpg)

**Comment by JAL9302** [comment]
Closing as in clicking the 'X' on its tab in the PowerShell ISE?

**Comment by treymorganthd** [comment]
yeah, this error occurs when I click on the 'X' and close the tab in ISE

**Comment by eamonoreilly** [comment]
This should be fixed in the latest source code. Once we publish this to the PowerShellGallery, you should not see this issue.
Thanks,
Eamon
