### ISSUE TITLE
Strange characters appearing in azure automation powershell scripts when ISE-addon is used

### ISSUE THREAD

**Issue by treymorganthd** [azureautomation/azure-automation-ise-addon#114]
When using the PowerShell ISE Add-on we are seeing that some scripts contain strange characters.  We are not sure why this is happening.  See screen shots uploaded.  If we remove the characters they just return over time.  
![strangecharactersise](https://cloud.githubusercontent.com/assets/19695323/15784061/70bb6b4a-2976-11e6-9d02-4b1eb5511218.jpg)

**Comment by treymorganthd** [comment]
![strangecharacterspsautomationwindow](https://cloud.githubusercontent.com/assets/19695323/15784176/f6fd2982-2976-11e6-8421-941df9c50aa4.jpg)
Here is what the azure automation screen looks like.  The prior image is how it looks in PS ise.

**Comment by eamonoreilly** [comment]
Hi Trey,
Could you add an sample of a script that contains these characters? Also, are these under any source control that might be doing something with the byte order mark?
Thanks,
Eamon

**Comment by treymorganthd** [comment]
Example Script sent to Joe Levy via email.

**Comment by eamonoreilly** [comment]
Hi Trey,
I uploaded the latest to https://www.powershellgallery.com/packages/AzureAutomationAuthoringToolkit/0.2.3.5 this morning that creates a BOM for new scripts created so hopefully this resolves this issue. Let me know if you still see this for new Runbooks created after you upgrade to 0.2.3.5.
Thanks,
Eamon
