### ISSUE TITLE
Cannot "Give Feedback"

### ISSUE THREAD

**Issue by TotallyInformation** [azureautomation/azure-automation-ise-addon#118]
Hi all, trying to send feedback via the interface and it resets every few seconds so that it is pretty impossible to actually enter anything.

**Comment by eamonoreilly** [comment]
Hi Julian,
What do you mean by reset? If you submit feedback, it will get sent to our back end service and then it will refresh afterwards so you could submit more feedback if you like? Do you see the "Thanks for giving feedback after you submit"?
Thanks,
Eamon

**Comment by TotallyInformation** [comment]
Hi Eamon, I did some more testing. The feedback form resets whenever it gets focus so if you swap to somewhere to copy some information and swap back, anything you've typed is lost.

When I was trying previously, it reset itself every few seconds which made it impossible to send anything.

**Comment by eamonoreilly** [comment]
Thanks - I'll look into fixing this.
Eamon

**Comment by eamonoreilly** [comment]
Hi Julian,
This should be fixed now. It will show up on PowerShellGallery when we do the next upload there.
Thanks again,
Eamon
