### ISSUE TITLE
usability problem

### ISSUE THREAD

**Issue by tdjastrzebski** [azureautomation/azure-automation-ise-addon#120]
It took me a while to find out that when I click "Upload Draft" and next "Test Draft in Azure" the draft being tested on window pop up is actually NOT the one I just uploaded.

Suggestion: after draft has been uploaded start a new job. Otherwise it can be confusing.

**Comment by eamonoreilly** [comment]
This should not be the case. When you upload a draft runbook to the service and then click on "Test Draft in Azure" it should be testing the one you just uploaded. Did you wait for the draft to be successfully uploaded before clicking on the button?
Thanks for the feedback on this,
Eamon

**Comment by eamonoreilly** [comment]
Closing this out. Please reopen if it is still an issue.
Thanks,
Eamon
