### ISSUE TITLE
Foreign langage issue

### ISSUE THREAD

**Issue by ghost** [azureautomation/azure-automation-ise-addon#122]
Hello,

I wanted to give a try with the Azure Automation ISE addon **0.2.3.5**
I'm using the "**Paiement à l'utilisation**" billing scenario, which means "**Pay as Go**" in french.

The "Toggle Prompt" doesn't work because of **quote** (`'`) terminator.

E.g.

> cd 'C:\Users\Administrator\AutomationWorkspace\Paiement à l`’`utilisation - 06f-----9c1\RES-GRP\RES-AUTOMAT';function prompt {'PS ' + $(Get-Location) + '> '}

**Comment by eamonoreilly** [comment]
Thanks for the feedback on this - we will have a look and hopefully fix for the next drop to the PowerShellGalley.
Eamon

**Comment by jennyhunter-msft** [comment]
A fix for this issue has been pushed to the master branch.
- Jenny
