### ISSUE TITLE
Parameters for my Azure Workbook was incorrect

### ISSUE THREAD

**Issue by FranckSix** [azureautomation/azure-automation-ise-addon#127]
```
Login-AzureRmAccount

$params = @{SqlServerName="myServer";SqlDatabaseName="myDb";SqlUserName="myDbUser"}

Register-AzureRmAutomationScheduledRunbook ` 
-Name "AutoExport" ` 
-ResourceGroupName "myAzureAutomation" ` 
-AutomationAccountName "myAutomation" ` 
-ScheduleName "mySchedule" ` 
-Parameters $params ` 
-ErrorAction Stop;
```

At end the parameters in portal contain quotes see file to screenshot. This make my workbook to fail.

![capture](https://cloud.githubusercontent.com/assets/8504152/21427372/39cfc2ca-c822-11e6-84d3-8429a6b59762.PNG)

**Comment by eamonoreilly** [comment]
I would open up a question on the automation forums on https://social.msdn.microsoft.com/forums/azure/en-US/home?forum=azureautomation to get some help on this as it is not specific to the add-on. 
Thanks,
Eamon
