### ISSUE TITLE
Following creds timeout, warning dialog box can be hidden and steals clipboard commands

### ISSUE THREAD

**Issue by silverl** [azureautomation/azure-automation-ise-addon#131]
Strangest problem has been plaguing me for several days. I'd come back to the computer after an absence, and copy/paste would stop working.

In the ISE Edit menu, the Ctrl-C and other clipboard operations were grayed out. Choosing Copy from the menu still worked (even though gray), as did right-clicking in the document window and choosing Copy from the context menu. 

If I used Ctrl-C (thinking it should work) a Ctrl-V would paste a text blob that looked suspiciously like the text you get when you do a Ctrl-C on a Windows dialog error message box.

Today I finally realized what had happened while Alt-Tabbing through all open apps.

The Azure credentials for the ISE plugin had timed out. One or more dialog boxes that resulted from the timeout were hiding in the task list.

The ISE continued functioning in all other regards that I could detect, but Ctrl-C would copy the contents of the dialog box instead of selected text.

In Windows 10, if you have many apps open, Alt-Tab may only show the most recently used apps. Others may not appear until you alt-tab through the visible tasks. Only then are other running apps or windows revealed. This is why I never noticed the dialog boxes.

If the auth dialog warnings could be made modal, this would avoid future confusion for many.

**Comment by eamonoreilly** [comment]
Thanks Larry. I'll look to make them modal as I think this is a good suggestion.
Eamon

**Comment by eamonoreilly** [comment]
Should be fixed with above check in. Closing for now.
Thanks for opening.
Eamon
