### ISSUE TITLE
[Enhancement] Add Module Asset visibility in plugin

### ISSUE THREAD

**Issue by mortenlerudjordet** [azureautomation/azure-automation-ise-addon#133]
Would like to see that some type of module visibility between local and AA be added in.
Just to give better understanding if one are using the same versions of modules when testing code.

Dream scenario would be to also sync modules between local and AA.

**Comment by eamonoreilly** [comment]
Thanks Morten I've had this one on my plate for a while https://github.com/azureautomation/azure-automation-ise-addon/issues/63 :-)
I'll see if I can get some time to actually implement it as I struggle with this sometimes myself.
Thanks again,
Eamon

**Comment by mortenlerudjordet** [comment]
Thanks Eamon, this plugin is my go to tool. But modules is my kryptonite, seem always to have mismatches between what I have tested with and what is deployed in AA. So lots of mental cycles used to debug code, when it's just a mismatch in one module or the other. 

Granted this is more a problem when the amount of modules in use becomes high, but I think having the number in your face will make it much easier to add it to the mental checklist. 

Thanks again for a great tool!

**Comment by eamonoreilly** [comment]
The latest version of the add-on now has support for modules Morten. Let me know if you run into issues with it.
Thanks,
Eamon

**Comment by mortenlerudjordet** [comment]
Sweet, looks good. Even handles dependencies. 

Though at a later stage maybe add some extra indication of what is happening on the ISE side (the spinning wheel does not give much visual feedback).
Tried updating a quite big module, and there were times I thought the update had timed out. 
Only to find in the portal that it was still extracting the module, though it is only cosmetics.

This is super useful, thanks again Eamon.
