### ISSUE TITLE
Error Configuring RunAs: Operation returned an invalid status code "forbidden"

### ISSUE THREAD

**Issue by Roblarson** [azureautomation/azure-automation-ise-addon#138]
I am receiving this failure when I log into the add-in and have the RunAs check box enabled. Account is a federated account with MFA required.
<img width="377" alt="iseaddonfailure" src="https://cloud.githubusercontent.com/assets/13791348/25601940/6491c3ce-2eb5-11e7-84a0-0014de5a19b2.png">

**Comment by eamonoreilly** [comment]
Hi Rob,
This error can occur if you don't have access to the AD service principal that was set up when the Azure Automation RunAs account was created.
Are you able to log in successfully to the Add-On when the RunAs is not checked?
Did you create the automation account with the RunAs using the same credential as you logged in as?
You could go to Azure AD and find the RunAs Service Principal and have the owner grant you admin access to this service principal if you were not the user that created it.

When the RunAs is selected, the add-on basically creates a local certificate on your computer and then attempts to add this certificate to the service principal in AD that was configured with the Automation RunAs account. It is useful if you want to have your scripts use the same Get-AutomationConnection -Name AzureRunAsConnection in your local environment and have it work. It also authenticates your local console session using this connection so you are working in the same environment that your automation scripts in the service would run. 
Thanks,
Eamon

**Comment by Roblarson** [comment]
Thanks that resolved the issue.

Robert Larson
Senior Architect
Secure Infrastructure – Azure Infrastructure Team
Microsoft Services
Cell: 281.827.9083

**Comment by eamonoreilly** [comment]
Thanks Robert. Closing issue.
