### ISSUE TITLE
Build from source instructions incomplete

### ISSUE THREAD

**Issue by Weishaupt** [azureautomation/azure-automation-ise-addon#140]
When I build from source, I'm unable to load the module, because important files like `AzureAutomationAuthoringToolkit.psd1`, `AzureAutomationAuthoringToolkit.psm1`, `AzureAutomationAuthoringToolkitConfig.json` and `AzureAutomationAuthoringToolkitInner.psm1` are missing in the root `AzureAutomationAuthoringToolkit` folder.

I temporarily copied those over from an old installation, but this should be part of the repository and instructions in the README.

**Comment by eamonoreilly** [comment]
Hi Marvin,
The instructions to build from source in the readme are:

> To build from source:
> Download or clone this repository, and extract from zip if necessary
> Open AutomationISE/AutomationISE.sln in Visual Studio
> Build the solution. NuGet will pull the required packages.
> Put the resulting binaries in the AzureAutomationAuthoringToolkit/ISEaddon directory
> Place the AzureAutomationAuthoringToolkit folder somewhere in your PSModulePath, ex: C:\Users\<USERNAME>\Documents\WindowsPowerShell\Modules

When you clone or download the source, you should get the AzureAutomationAuthoringToolkit\ISEaddon directory also. Once you have built the add-on binaries, you should be able to copy them from the AutomationISE\bin\debug folder and place them in the AzureAutomationAuthoringToolkit\ISEaddon\ folder where the binaries-go-here.txt file is. You can then place this module in your PSModulePath or import the addon directly by running Import-Module C:\azure-automation-ise-addon-master\AzureAutomationAuthoringToolkit\AzureAutomationAuthoringToolkit.psd1

Did you follow these steps or did you do it a different way?
Thanks for opening up this issue,
Eamon

**Comment by Weishaupt** [comment]
Hey Eamon,
I must admit, that I was a bit blind regarding the folder where to put the compiled binaries. I've created a pull request, that makes the copying step more explicit. Thank you for the explanation.

**Comment by eamonoreilly** [comment]
Thanks Marvin,
If you submit the pull request, I'll accept it in to update the readme. Thanks for working on this.
Eamon

**Comment by eamonoreilly** [comment]
Closing this issue out with the suggested change https://github.com/azureautomation/azure-automation-ise-addon/commit/b46b8e713dd2468f9762a5421f9ea9c73039f9b8 
Thanks,
Eamon
