### ISSUE TITLE
Pass-Through Authentication not working - why?

### ISSUE THREAD

**Issue by silverl** [azureautomation/azure-automation-ise-addon#142]
Any idea why pass-through auth does not work in the authentication popup when signing in? We use ADFS. I am prompted with our organization's login page (username/password) instead of being automatically logged in.

What kind of browser container is being used to prompt for authentication? Does this container not allow pass-through?

Thanks.

**Comment by eamonoreilly** [comment]
I set the prompt behavior to "Always" as some users wanted to be able to switch between different logins during the session. I could resolve this by either adding a switch user button or toggling the existing login button to switch user once someone logs in.
I'll have a look at tweaking this behavior.
Thanks for the feedback,
Eamon

**Comment by eamonoreilly** [comment]
This should enable pass through authentication where available. It will show up on the next release on the PowerShell gallery or you can build from source if you want to try it out before then.
Thanks again,
Eamon

**Comment by silverl** [comment]
I've confirmed the fix works. Thank you very much!
