### ISSUE TITLE
file path not able to contain certain special characters

### ISSUE THREAD

**Issue by AlBroughEAT** [azureautomation/azure-automation-ise-addon#145]
Special characters, such as a colon (:) in our case, are added by our Tier 1 Azure CSP provider as a part of their naming convention to the subscription name. The special character is not handled by the Azure Automation ISE Add-on and throws an error when trying to create the directory with the special character

**Comment by AlBroughEAT** [comment]
Eamon has added code to handle this. Many thanks

**Comment by eamonoreilly** [comment]
Fix is checked with commit https://github.com/azureautomation/azure-automation-ise-addon/commit/a5a36b273129b12ad9e510bdaa0aa84fcadb8fd2  
closing
