### ISSUE TITLE
Hyphen Issue when importing assets 

### ISSUE THREAD

**Issue by ahmadabdalla** [azureautomation/azure-automation-ise-addon#150]
If an Azure subscription name contains a Hyphen that acts as a word connector. It breaks the import process: 
Ahmad **–** Abdalla (Not OK)
Ahmad **-** Abdalla (OK).

![image](https://user-images.githubusercontent.com/28486158/39737349-ef70ae2e-52c7-11e8-8860-684befd863bf.png)

This is the error that you get:
![image](https://user-images.githubusercontent.com/28486158/39737372-0a3bcd56-52c8-11e8-85fb-d24d8e14737b.png)

![image](https://user-images.githubusercontent.com/28486158/39737449-8220db90-52c8-11e8-9e8a-0c72b916a287.png)

**Comment by ahmadabdalla** [comment]
I've fixed the issue manually by editing the module AzureAutomationAuthoringToolkitInner.psm1 .

Edited the function 'Get-AzureAutomationAuthoringToolkitConfiguration'

Added the below lines before writing the function output:
$Configuration.LocalAssetsPath = $Configuration.LocalAssetsPath.Replace('â€“','–')
$Configuration.SecureLocalAssetsPath = $Configuration.SecureLocalAssetsPath.Replace('â€“','–')

**Comment by eamonoreilly** [comment]
Thanks for opening up this issue. I believe I have addressed this in the above fix. It should show up on the gallery with the next fix.
Thanks,
Eamon

**Comment by eamonoreilly** [comment]
I created a release to address this issue. It is available on the [PowerShell Gallery](https://www.powershellgallery.com/packages/AzureAutomationAuthoringToolkit/0.2.4.2)
If you still see the issue, please reopen.
Thanks for reporting,
Eamon
