### ISSUE TITLE
Select-AzureSubscription no longer exists, so login fails

### ISSUE THREAD

**Issue by silverl** [azureautomation/azure-automation-ise-addon#155]
In the latest Azure RM Powershell modules (6.5.0) they appear to have deprecated `Select-AzureSubscription`.

This needs to be detected on/around AutomationISE/AutomationISEControl.xaml.cs:901 and worked around.

The plugin is broken if the user has upgraded AzureRm recently.

**Comment by silverl** [comment]
Perhaps replaced with `Select-AzureRmContext` 
https://docs.microsoft.com/en-us/powershell/module/azurerm.profile/Select-AzureRmContext?view=azurermps-6.5.0

**Comment by eamonoreilly** [comment]
Thanks for binging this up. Just changed this to use Set-AzureRMContext. Will do an official build next week.
