### ISSUE TITLE
Unable to pull down runbooks

### ISSUE THREAD

**Issue by wsmelton** [azureautomation/azure-automation-ise-addon#156]
Upon login to my Azure Subscription I am getting this error from PowerShell ISE:
![image](https://user-images.githubusercontent.com/11204251/43653344-60198f0e-970d-11e8-8882-a4e42b229609.png)

It will not actually show the current runbooks I have under the Automation account. I am logging in as the subscription owner so it is not a permissions issue.

**Comment by eamonoreilly** [comment]
Is there any error in the status window? If you uncheck the RunAs, does it work correctly? I haven't seen this issue so I'll need to investigate some more. Is it consistent across different automation accounts?
Thanks for reporting,
Eamon

**Comment by wsmelton** [comment]
Nothing show as error in the status window:
![image](https://user-images.githubusercontent.com/11204251/43666272-c674db7a-9738-11e8-8c7b-ec1a83643a63.png)

**Comment by wsmelton** [comment]
I switch to a brand new runbook that I just created and the same bad request prompt is given. I have also unchecked RunAs and the error prompt does not show up, but I'm still missing the assets under runbooks and DSC.

**Comment by eamonoreilly** [comment]
Can you uncheck the Run As box and then sign in again? I'm hoping that the code path that gets executed outside of the RunAs path would produce a better error?
Also, an option would be to build the add on locally if you have Visual Studio installed and see what line it is failing on. I could also jump on a skype call also if neither of the above work.
thanks,
Eamon

**Comment by wsmelton** [comment]
Unchecking the runas I did previously. It does not provide any error prompt or additional info on the status box.

**Comment by artisticcheese** [comment]
Happening to me too.

**Comment by eamonoreilly** [comment]
Thanks guys. I think I have found the issue. There is a new way to add a credential to an existing AD application and the way I do it currently is no longer supported. This involves moving to a new AD client nuget package so might take me a little time and then to change the code as needed.
Thanks,
Eamon

**Comment by eamonoreilly** [comment]
I created a release to address this issue. It is available on the [PowerShell Gallery](https://www.powershellgallery.com/packages/AzureAutomationAuthoringToolkit/0.2.4.2)
If you still see the issue, please reopen. 
Thanks again guys for reporting.
Eamon
