### ISSUE TITLE
Changing the editor-to-use in the add-on to use VS Code

### ISSUE THREAD

**Issue by obeliskm** [azureautomation/azure-automation-ise-addon#157]
I've built 0.2.4.1 from git with visual studio, copied the exe into the module directory, and it seems to largely work when I run addon.exe from a powershell window (logs in, downloads assets, and so forth).

The only problem I have is that the only option available in the "Editor to use" field is Visual Studio.  I've got VS Code installed, what I'm missing is the understanding of how to glue the addon.exe and vs code together so that I get something like the screenshot in https://github.com/azureautomation/azure-automation-ise-addon/blob/master/Screenshots/VSCodeAddOn.png - can somebody point a noob vs code user in the right direction?

Cheers

**Comment by eamonoreilly** [comment]
The code that looks to see if VS Code is installed is
`        private string GetVSCodePath()
        {
            using (Microsoft.Win32.RegistryKey VSCodeKey = Microsoft.Win32.Registry.LocalMachine.OpenSubKey(@"SOFTWARE\Classes\Applications\Code.exe\shell\open\command"))
            {
                if (VSCodeKey != null)
                {
                    var codeValue = VSCodeKey.GetValue("").ToString();
                    return (codeValue.Substring(0, codeValue.IndexOf('%') - 1).Replace("\"", string.Empty).Trim());
                }
                return null;
            }
        }`
Can you check that SOFTWARE\Classes\Applications\Code.exe\shell\open\command exists on your system?
The integration with VS code is really only through the AddOn UI standalone where you can open up runbooks / copy assets over etc. 
I usually just resize my VS code window so that I have the AddOn window sitting beside it so I can work on both together.
Thanks,
Eamon

**Comment by obeliskm** [comment]
Yes, SOFTWARE\Classes\Applications\Code.exe\shell\open\command exists on my machine, it points to 

`"<path-to-my-homedir>\AppData\Local\Programs\Microsoft VS Code\Code.exe" "%1"`

I've updated to 0.2.4.2, it behaves the same.  With either version, when I run the addon, in the "Editor to use" drop down "Visual Studio" appears twice
 
![image](https://user-images.githubusercontent.com/43050059/45269679-fffbc280-b4e5-11e8-8318-b71a027eb5e5.png)

uninstalling Visual Studio just gives me an empty drop down, reinstalling VS Code doesn't help.  So close :-(

Cheers
Simon

**Comment by eamonoreilly** [comment]
Hi Simon,
I made a fix also look in the current user registry as VS Code can now be installed there as well as system wide.
 Could you give it a go and see if it addresses your issue?
Thanks,
Eamon

**Comment by obeliskm** [comment]
Woohoo!

![image](https://user-images.githubusercontent.com/43050059/45523971-3146fc00-b820-11e8-8625-d4777e3db691.png)

Thanks Eamon!
