### ISSUE TITLE
object reference not set to instance when uploading

### ISSUE THREAD

**Issue by Stijnc** [azureautomation/azure-automation-ise-addon#16]
![aa- ise error](https://cloud.githubusercontent.com/assets/1662677/9254531/4a61dc06-41e4-11e5-84e1-c4faef98c745.PNG)

**Comment by alstab** [comment]
@Stijnc , we've made a lot of changes since last week and I haven't repro'd since. Hang tight for a new release and we can see if it's working for you then, or try building the latest version yourself if you're curious.

**Comment by eamonoreilly** [comment]
Can you try with the most recent build. We have not seen this in our environment. Thanks
