### ISSUE TITLE
Bug: VSCode installed on user and not machine will not show GUI option

### ISSUE THREAD

**Issue by mortenlerudjordet** [azureautomation/azure-automation-ise-addon#161]
In AddOn solution in AutomationISEControl there is a bug when VSCode is installed in user context.
The validation of path will return null and not add the VSCode option in GUI.

Changed the code to the following:
GetVSCodePath:
```
        private string GetVSCodePath()
        {
            using (Microsoft.Win32.RegistryKey VSCodeKey = Microsoft.Win32.Registry.LocalMachine.OpenSubKey(@"SOFTWARE\Classes\Applications\Code.exe\shell\open\command"))
            {
                if (VSCodeKey != null)
                {
                    var codeValue = VSCodeKey.GetValue("").ToString();
                    return (codeValue.Substring(0, codeValue.IndexOf('%') - 1).Replace("\"", string.Empty).Trim());
                }
                else
                {
                    using (Microsoft.Win32.RegistryKey VSCodeCurrentUserKey = Microsoft.Win32.Registry.CurrentUser.OpenSubKey(@"SOFTWARE\Classes\Applications\Code.exe\shell\open\command"))
                    {
                        if (VSCodeCurrentUserKey != null)
                        {
                            var codeValue = VSCodeCurrentUserKey.GetValue("").ToString();
                            return (codeValue.Substring(0, codeValue.IndexOf('%') - 1).Replace("\"", string.Empty).Trim());
                        }
                        else
                        {
                            return null;
                        }
                    }
                }
            }
        }
```

**Comment by eamonoreilly** [comment]
Hi Morten,
Were you using an older build? I thought this was fixed with https://github.com/azureautomation/azure-automation-ise-addon/commit/93f2869907db7e5d5ee615493c1a9b85d89e0d91
Thanks,
Eamon

**Comment by mortenlerudjordet** [comment]
Yes, that was the code I was running. Though after running through a debug pass on the machine I had a new install of VSCode on it seemed to always return null to the caller even if it took the path through the added code. 

I suspected the return null; on line 1583 was the culprit. 
After tucking it behind the else I got the correct behavior of it returning the path (user install location) to the caller and not just null as before.

Not a big c# person, but the code does not seem to return after
```return (codeValue.Substring(0, codeValue.IndexOf('%') - 1).Replace("\"", string.Empty).Trim());```
but continue on and also run:
```return null;```

Morten

**Comment by eamonoreilly** [comment]
The return call will always exit once it goes into that if statement so the code you have looks equivalent to what is there. I also could not reproduce this behavior locally? Could you give it try with the old code once more and see if it still repros for you?
Thanks,
Eamon

**Comment by mortenlerudjordet** [comment]
I tried a reset of the repo and did another debug run, this time no problem.
So seems this was only on my end.

Sorry for taking your time.
I will close this now

**Comment by mortenlerudjordet** [comment]
Not a bug
