### ISSUE TITLE
dash gets replaced with 'funky' chars

### ISSUE THREAD

**Issue by Stijnc** [azureautomation/azure-automation-ise-addon#17]
## original in Azure

![error 2](https://cloud.githubusercontent.com/assets/1662677/9254583/95ccaebe-41e4-11e5-94ee-79869313aea8.PNG)
## downloaded:

Get-AzureVM | where{$_.status -ne 'StoppedDeallocated' -and $_.Name -notin $exceptionlist} | Stop-AzureVM â€“force

**Comment by eamonoreilly** [comment]
Can you check this with the cmdlets or the portal and see if this shows up there? We have not been able to reproduce this. Do you have a script where this happens every time that you could share?

**Comment by JAL9302** [comment]
I was seeing something similar with quotation marks last week.

**Comment by justinmetz** [comment]
I'm experiencing this as well..  It seems to only happen when a fresh script is uploaded to Azure Automation.  If the script is created outside of the ISE and downloaded (then re-uploaded) it doesn't seem to be affected.  Hopefully that helps...

**Comment by eamonoreilly** [comment]
Closing this out as I believed it is addressed with the fix in June. If you are still seeing this, please reopen and I can investigate further. Thanks guys.
Eamon
