### ISSUE TITLE
Add a search box in runbooks that searches across Name / Status / Sync Status and description

### ISSUE THREAD

**Issue by eamonoreilly** [azureautomation/azure-automation-ise-addon#20]
As the runbook list gets large, it is difficult to find the runbook you want to work on.

**Comment by alstab** [comment]
Fixed with 70b2097f8c5932ae6128dc05656386c4712856e4

**Comment by alstab** [comment]
Ignoring description for now, though, since it's not surfaced in the UI. Perhaps we can open a separate issue for that.

**Comment by alstab** [comment]
Also I went a little overboard :)
