### ISSUE TITLE
Add connections to assets

### ISSUE THREAD

**Issue by eamonoreilly** [azureautomation/azure-automation-ise-addon#22]
It would be nice to have connection assets available in the add on also as I use these more now that additional modules are starting to include connection assets like the OMS and Azure AD modules on https://github.com/tiander/OMSsearchAPI

**Comment by jefffanjoy** [comment]
This is definitely a necessity.  Any of my runbooks that use modules that expose connections require this which is many as I do a fair amount of integration with SharePoint Online.

**Comment by JAL9302** [comment]
This is now in the latest build
