### ISSUE TITLE
Add way to create runbook via button

### ISSUE THREAD

**Issue by JAL9302** [azureautomation/azure-automation-ise-addon#24]
From Prasad: 
No way in the UI to create a new runbook locally. I found out from Joe on how to do this (create a ps1 file in the specific share). Having a button in the UI will make it easy

**Comment by JakobGSvendsen** [comment]
was about to add this too. should be faily easy to implement, and It makes it possible to do all work from ISE

**Comment by alstab** [comment]
@robplank is interested in this as well
