### ISSUE TITLE
Make cred expiration more manageable

### ISSUE THREAD

**Issue by JAL9302** [azureautomation/azure-automation-ise-addon#26]
I think there should be a refresh token we should be able to use to keep the user connected instead of making them log in again?

From Prasad:    The credentials were expired after sometime. I am sure this is not something the add-on controls – but if there was any button or popup like “Your credentials is about to expire – Click here to renew…” This will save a login again (and yes from 2FA)

**Comment by eamonoreilly** [comment]
Added a timer to check if token is about to expire and then refreshes it. This should help with the credential expiring after about an hour.

**Comment by robplank** [comment]
@eamonoreilly is this fix included with v0.2.1? reason I ask is after leaving v0.2.1 open over the weekend this is what happens
![image](https://cloud.githubusercontent.com/assets/12474044/9579162/02c0134c-4fb6-11e5-8ea1-231c6b2c6706.png)
