### ISSUE TITLE
when "Upload Draft" if clicked and the file is not saved (it has the *) user should be warned

### ISSUE THREAD

**Issue by JakobGSvendsen** [azureautomation/azure-automation-ise-addon#28]
I have several times forgot to save the file, and then clicked "upload draft". then it uploads the saved version instead of the edited one which I forgot to save.

would be great with a warning if one try to upload a draft that is not saved.
or a messagebox where user can choose to click "OK" and it saves the file and uploads, or "Cancel"

**Comment by eamonoreilly** [comment]
this should be addressed now in the code. Alex, you may want to look and update as needed.

**Comment by alstab** [comment]
Slightly altered behavior and strings, checking in now
