### ISSUE TITLE
Option to insert assets from the Addon

### ISSUE THREAD

**Issue by JakobGSvendsen** [azureautomation/azure-automation-ise-addon#29]
Would be great to have the option to automatically insert the assert code as in the web portal editor.

Could be a right click menu on the asset in the list of assets with option to insert "Set" or "Get" code.

Or a button.

**Comment by eamonoreilly** [comment]
Added button to insert asset into current opened file. Only does "Get" but since we only have set on variables and it is not used as often I left it out for now to simplify usage.
