### ISSUE TITLE
Disable Start New Job button from test job window if the runbook is running

### ISSUE THREAD

**Issue by eamonoreilly** [azureautomation/azure-automation-ise-addon#30]
Can check for any final states (response.Job.Properties.Status !=  "Completed"  && response.Job.Properties.Status != "Failed" && response.Job.Properties.Status != -ne "Suspended") and then activate the Start New Job button again.

**Comment by alstab** [comment]
Done. One comment for anyone wondering: suspended is not technically a final state, so entering this state will not re-enable the start job button. The test job must be stopped first.
