### ISSUE TITLE
If you try and select variables or credentials from the assets tab before logging in it will crash the ISE

### ISSUE THREAD

**Issue by eamonoreilly** [azureautomation/azure-automation-ise-addon#32]
We should catch the case where a user clicks on the assets tab and selects variable or credentials without logging in first.

**Comment by alstab** [comment]
This is avoided with a3684f60089df0c9ca0738aeb2f28dce271c01c1 but perhaps not truly fixed.

**Comment by eamonoreilly** [comment]
Looks good to me. Closing bug!
