### ISSUE TITLE
Install throws a COM exception

### ISSUE THREAD

**Issue by atchutbarli** [azureautomation/azure-automation-ise-addon#36]
Please check the attached snap shot. Install is throwing a COM Exception: Unable to cast COM component  CERTENROLLLib.CX509PrivateKey   for the interface with ID"72*..." failed due to the following error. No such interface supported

![iseinstallerror](https://cloud.githubusercontent.com/assets/5118968/9447494/850ad716-4a4c-11e5-93e5-6c8b66abeeb9.PNG)

**Comment by alstab** [comment]
@eamonoreilly @jodoglevy any ideas? Sounds certificate related?

**Comment by JAL9302** [comment]
maybe a .net version issue?  @atchutbarli what .net version are you using?

**Comment by eamonoreilly** [comment]
I actually think it is a build issue related to not having the interop types for certenrolllib embedded in the binary. Doing a little more digging to confirm how the project was built as I don't see it when I build on my environment.

**Comment by alstab** [comment]
Eamon and I just investigated and it seems to have something to do with the "embed interop types" option causing issues when building/running on different OSs.  We will investigate a little more but I am about to check in a fix.

**Comment by alstab** [comment]
Upon further investigation this doesn't seem to have been fixed.

**Comment by atchutbarli** [comment]
thank you!
