### ISSUE TITLE
If local copy of runbook and cloud copy are in Sync don't prompt to overwrite when user clicks download

### ISSUE THREAD

**Issue by robplank** [azureautomation/azure-automation-ise-addon#38]
Currently if you click download and already have an existing copy of the runbook, you receive a popup asking if the local copy should be overwritten. 

Desired solution would be to have the download button check the last modified times of the local version and the cloud version and if they match do nothing, if the cloudy version is newer then notify that any local changes will be lost.

**Comment by alstab** [comment]
good catch @robplank
