### ISSUE TITLE
Azure Automation ISE add-on module should be available via the PowerShell Gallery

### ISSUE THREAD

**Issue by pcgeek86** [azureautomation/azure-automation-ise-addon#4]
# Issue

The Azure Automation ISE add-on module should be available in the PowerShell Gallery.
# Symptom

The following PowerShell command does not return the Azure Automation ISE add-on.

``` powershell
Find-Module -Name *Azure*;
```
# Expected Result

The following PowerShell command should return and install the Azure Automation ISE add-on module:

``` powershell
Find-Module -Name AzureAutomationISE | Install-Module -Scope CurrentUser;
```

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by alstab** [comment]
Thanks Trevor. We'll definitely do this, but want to wait until the add-on is slightly more stable.

**Comment by JAL9302** [comment]
The ISE add on is now available on the PowerShell Gallery: https://www.powershellgallery.com/packages/AzureAutomationAuthoringToolkit/. Please test and let me know what you think @pcgeek86.

**Comment by JAL9302** [comment]
One known issue: The PowerShell ISE must be run as an administrator for the Azure Automation ISE add on to work.

**Comment by pcgeek86** [comment]
@jodoglevy Thanks Joe. Good to know it made its way onto the gallery. I'll check it out.

Cheers,
Trevor Sullivan
