### ISSUE TITLE
Test Draft in Azure can fail

### ISSUE THREAD

**Issue by robplank** [azureautomation/azure-automation-ise-addon#40]
~~Please update the UI so it is clear that the initial load is a previous test job.~~ [this is now being tracked in issue 72]

there might also be a bug where the previous test job is still running and you have uploaded a new draft, when testing your corrected draft you still see the output/test panel from the previous job.

Created from conversation with @alstab

**Comment by robplank** [comment]
@alstab I think I found how to reproduce the Draft test bug, here is a screen shot of the Runbook in Azure, local copy in ISE and the error message when i try to test the draft
![image](https://cloud.githubusercontent.com/assets/12474044/9560434/440ba494-4dd9-11e5-822d-886cb9e8fdad.png)

i have done this two times by having typos in the word workflow or mandatory, waited over 10 mins and tried testing again, get the same error message.

not sure if you want to leave this as part of issue #40 or want to create a new issue

**Comment by alstab** [comment]
I have not been able to repro but my recent changes should mitigate this. Following up offline with Rob to discuss and closing the issue.
