### ISSUE TITLE
Bugbash:  AuthorizationFailed, cannot read resource groups in scope

### ISSUE THREAD

**Issue by rebro-msft** [azureautomation/azure-automation-ise-addon#42]
Repro steps:
1.  Open ISE plugin.
2.  Try sign in with account:
         oaastestdf43@live.com
         [usual password]
3.  It says it could not retrieve the automation accounts, with the attached image popup message.

![errormsg](https://cloud.githubusercontent.com/assets/10780862/9587489/a3a31a72-4fd7-11e5-825c-63cca1f6194d.PNG)

**Comment by alstab** [comment]
This looks like an issue with how that particular account is set up. If you log in to the portal as that account, it doesn't appear to have any resources.

**Comment by eamonoreilly** [comment]
Closing as not repro for now. Will follow up on this specific account to see if there is anything else going on.
