### ISSUE TITLE
Sign in cancels if username in ISE add-on doesn't match username used in Azure Auth 

### ISSUE THREAD

**Issue by elcooper** [azureautomation/azure-automation-ise-addon#44]
Repro steps: 
1.  leave old username in the ISE add-on
2. click "sign-in"
3. use different username and password
4.  update text on bottom reads:
 " Launching login window...
User cancelled sign-in."

Updating the username in the box correctly logs in. 

![ise-bug](https://cloud.githubusercontent.com/assets/10818658/9587760/1418bde2-4fd9-11e5-9147-06b8461c6b1b.png)

**Comment by alstab** [comment]
Eamon has fixed this with 342eee6d6d55f9905cbb25aea77eed9f207ce984
