### ISSUE TITLE
Bugbash: Old message remains

### ISSUE THREAD

**Issue by rebro-msft** [azureautomation/azure-automation-ise-addon#46]
Repro Steps:
1. Login to the ISE with an account that does not contain an automation account.
2. Go to the portal and create an automation account.
3. Log in again to get it to re-retrieve the account's automation accounts.
4. Old message saying "no accounts found, create one" remains under the message "retrieving automation accounts, please wait."  It is a little confusing.

![ui-oldmsgremains](https://cloud.githubusercontent.com/assets/10780862/9587901/f9d7dfa2-4fd9-11e5-9f70-2a1dcd63de94.PNG)

**Comment by eamonoreilly** [comment]
Need to think about this one a little as the status bar is used to show actions taken but I can see clearing this for some scenarios while new ones are running. Alex - lets discuss.
