### ISSUE TITLE
Bugbash: Only some subscriptions are picked up.

### ISSUE THREAD

**Issue by rebro-msft** [azureautomation/azure-automation-ise-addon#49]
In the azure DF portal there are 2 subscriptions:

![portal-subscriptions](https://cloud.githubusercontent.com/assets/10780862/9588161/84cfaefe-4fdb-11e5-8705-18b040b708fb.PNG)

But in the ISE, it is only picking up one:

![ise-subscriptions](https://cloud.githubusercontent.com/assets/10780862/9588105/3328b668-4fdb-11e5-8f70-6dcd03d57b95.PNG)

**Comment by eamonoreilly** [comment]
If this still reproduces, please let me know and I'll have a look at your environment.
