### ISSUE TITLE
SMA support

### ISSUE THREAD

**Issue by bgelens** [azureautomation/azure-automation-ise-addon#5]
A lot of my customers are struggling with SMA and Azure Pack RP as front end.
Some even just have Azure Pack to have a front-end for SMA.
The RP editing experience however is not good for long complicated runbooks.
Would be awesome if this extensions would have SMA support as well. This would tie in nicely with Git as well.

**Comment by eamonoreilly** [comment]
Closing this out Ben since this is now available for SMA in System Center 2016 TP5 https://blogs.technet.microsoft.com/orchestrator/2016/04/28/introducing-service-management-automation-ise-add-on/

**Comment by bgelens** [comment]
Make sense :-) Thanks for this awesome Add-on!
