### ISSUE TITLE
Bugbash: path for syncing runbooks is long - don't change directory to sync folder

### ISSUE THREAD

**Issue by elcooper** [azureautomation/azure-automation-ise-addon#50]
Since the generated file path for storing runbooks is really long, it is hard to author & test cmdlets in the directory where runbooks are synced to.  Since I don't need to be in the same directory to author an test in the ISE, I would prefer that we don't automatically change paths.  

![image](https://cloud.githubusercontent.com/assets/10818658/9588343/8e0773e8-4fdc-11e5-8f20-e522b4459ac7.png)

**Comment by eamonoreilly** [comment]
I was wondering if people would want this or not. I added it so that I could easily create new runbooks like below and not get confused where I created them or what state they might be locally compared to in the cloud.

echo . > MyNewRunbook.ps1
ise MyNewRunbook.ps1

and start authoring & testing it there and know it is in the right folder. We can discuss more and see what people think.

**Comment by robplank** [comment]
I would say it is not clear how to create a new runbook locally (ISE), If I click on New in the ISE create my workflow/runbook and click save it defaults to the last path I saved a file to in ISE, not the working Path of ISE or the Account content location.

I would suggest a Create New Runbook button that reads the content location path and saves to it then the upload process

**Comment by alstab** [comment]
If the only complaint about changing the working directory is that the path is too long, then why not simply define a custom prompt?

You can do so with `function prompt {"PS myprompt> "}`, for instance, which would change your prompt to (write-output command added as an example):
`PS myprompt> Write-Output "Hello!"`

**Comment by alstab** [comment]
Also, @robplank , I agree with your comment, but I have deleted it since it is being tracked separately in issue #24

**Comment by alstab** [comment]
As discussed offline with @eamonoreilly and @elcooper , we've decided to modify the prompt with a "path hint", e.g. `PS C:\...\[CurrentAccountName]>`
