### ISSUE TITLE
Bugbash: The gears icon continues to animate, even after action is completed.

### ISSUE THREAD

**Issue by rebro-msft** [azureautomation/azure-automation-ise-addon#51]
It says "Downloading...", then says "Downloaded", but icons still spin.

**Comment by eamonoreilly** [comment]
Alex might have to get repro steps Rebecca from you as I don't see that happening in my environment.
Thanks,
Eamon

**Comment by alstab** [comment]
I have found and fixed a number of places in the code where this could have occurred (all that I am aware of). I'm closing this now since I have not seen the issue for a long time.
