### ISSUE TITLE
Asset Type selector is not prominent enough

### ISSUE THREAD

**Issue by alstab** [azureautomation/azure-automation-ise-addon#54]
On the Assets tab, it's too easy to forget about selecting an Asset Type.

Possible solutions:
- Add a label to the selector
- Add default text to the selector
- Add a default selection to the selector
- Some combination of the above

**Comment by eamonoreilly** [comment]
Updated this to automatically select credentials when an automation account is selected since credentials are probably more common than variables initially. This should make it more visible to users since they will see their credentials and then could select variables
