### ISSUE TITLE
Exception: Resource Group not found

### ISSUE THREAD

**Issue by pcgeek86** [azureautomation/azure-automation-ise-addon#56]
If you switch between subscriptions too fast (before the background task completes), using the combo box, you get an error saying that a resource group can't be found.

![image](https://cloud.githubusercontent.com/assets/466713/9963614/5f18b2de-5de9-11e5-8b13-6246b0db4698.png)

Cheers,
**Trevor Sullivan**
Microsoft MVP PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by eamonoreilly** [comment]
Duplicate of https://github.com/azureautomation/azure-automation-ise-addon/issues/53 Trevor. I believe Alex is going to fix this for the next release.

**Comment by pcgeek86** [comment]
@eamonoreilly Sorry, missed that.
