### ISSUE TITLE
Shorten the "account content location" path 

### ISSUE THREAD

**Issue by pcgeek86** [azureautomation/azure-automation-ise-addon#57]
I happen to love the fact that the add-on is using the subscription name **and** subscription ID in the folder naming, **but**:
1. I suspect that you will quickly encounter issues with long file paths. 
2. Users can change their subscription names, which could potentially expose a software bug. I haven't tested this scenario yet.

You may want to consider a more concise / predictable convention. 

![image](https://cloud.githubusercontent.com/assets/466713/9963671/a0ea05f0-5de9-11e5-9be7-d56d03d75165.png)

Cheers,
**Trevor Sullivan**
Microsoft MVP PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by eamonoreilly** [comment]
The option would be to remove the subscription name but I think that would remove some of the discoverability on what subscription you are using. I think I will leave as is for now and see if other users encounter any issues over time. If they change their subscription name, then it should create a new folder and they can sync down from the cloud again or copy from their previous folder.
I'll leave open for awhile and see if any issues arise.
Thanks.

**Comment by pcgeek86** [comment]
@eamonoreilly 

I agree that it would hurt discoverability. That is why I started off with a disclaimer that I loved how it currently is. Verbosity, in my opinion, is preferable to terseness. Good job, but just be aware of the potential implications.

Cheers,
**Trevor Sullivan**
Microsoft MVP PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by eamonoreilly** [comment]
Closing as we have not seen issues from other users on this.
