### ISSUE TITLE
When I click the "change" button, I expect to be prompted for a certificate

### ISSUE THREAD

**Issue by pcgeek86** [azureautomation/azure-automation-ise-addon#58]
# Problem

When I click the "change" button, a message is printed that indicates the certificate thumbprint has been "updated."

![image](https://cloud.githubusercontent.com/assets/466713/9963773/20874994-5dea-11e5-82a8-d5700683cbe3.png)
# Expected Result

When I click the "change" button, my natural expectation is to be prompted to select a certificate, from the user or computer certificate store.

Cheers,
**Trevor Sullivan**
Microsoft MVP PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by eamonoreilly** [comment]
Good idea Trevor. I'll look to add that for a future release.

**Comment by pcgeek86** [comment]
Added in this commit: https://github.com/azureautomation/azure-automation-ise-addon/commit/9938c61507ecaab722b09ec7e7977154675c5fa3
