### ISSUE TITLE
Don't change PowerShell prompt function

### ISSUE THREAD

**Issue by pcgeek86** [azureautomation/azure-automation-ise-addon#59]
Not cool. I never explicitly asked for my PowerShell `prompt` function to be updated. Hence, Azure Automation should not be doing that. Environmental changes are, generally speak, bad, unless the user has "opted in."

![2015-09-18 10_28_06-cortana](https://cloud.githubusercontent.com/assets/466713/9964877/03a85484-5df0-11e5-903c-97384f805dc1.png)

Cheers,
**Trevor Sullivan**
Microsoft MVP PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by alstab** [comment]
This has been mitigated with 7031557010c92ebfe125a0c171e65938a48d7024 by giving an easy option to change the prompt back.

For now, we are leaving the default as-is, based on positive feedback from others.

**Comment by eamonoreilly** [comment]
Closing that we have a toggle button now to go back to standard prompt.
