### ISSUE TITLE
Login fails via corporate bluecoat proxy

### ISSUE THREAD

**Issue by mattduguid** [azureautomation/azure-automation-ise-addon#6]
When attempting to "Sign in Azure Automation" using a login with MFA enabled, I get the standard prompt in the MFA app to verify the login but when it returns to the ISE it provides a "Status" of "User cancelled sign in". The same account with MFA has no issue login into the standard Azure portal.

![image](https://cloud.githubusercontent.com/assets/7642305/9125679/10b43aea-3cf7-11e5-9908-c204c636a458.png)

**Comment by eamonoreilly** [comment]
Hi Matt,
Can you try with the latest builds? I have 2FA enabled on our work accounts and I was able to login using phone authentication successfully. Please reopen if you are still seeing issues with this.
Thanks,
Eamon

**Comment by mattduguid** [comment]
Latest build compiled and deployed and still same issue

**Comment by eamonoreilly** [comment]
Thanks Matt. I added a little more error information to the status window. Can you see what error message is written out now when you try and log in?
Thanks again.

**Comment by mattduguid** [comment]
Hi Eamon, same error no additional output.
![usercanceledsignin](https://cloud.githubusercontent.com/assets/7642305/9296302/2b84d584-44de-11e5-8e19-71ee916ede9e.jpg)

**Comment by eamonoreilly** [comment]
Hi Matt. Can you set a breakpoint in the last catch below in the AutomationISEControl.xaml.cs below and see what information is in the exception Ex?
Thanks,
Eamon
            catch (Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException Ex)
            {
                UpdateStatusBox(configurationStatusTextBox, Properties.Resources.CancelSignIn +  " Error code: " + Ex.ErrorCode.ToString() + " Error Message: " + Ex.Message);
            }
            catch (Microsoft.IdentityModel.Clients.ActiveDirectory.AdalException Ex)
            {
                UpdateStatusBox(configurationStatusTextBox, Properties.Resources.CancelSignIn + " Error code: " + Ex.ErrorCode.ToString() + " Error Message: " + Ex.Message);
            }
            catch (Exception Ex)
            {
                var detailsDialog = System.Windows.Forms.MessageBox.Show(Ex.Message);
            }

**Comment by mattduguid** [comment]
That showed up the cause. We've seen it on this customer site before with DirSync and Visual Studio 2013. 

The initial login to Azure screen goes through the proxy fine, after that the additional output shows an access denied from the corporate Bluecoat proxy.

![proxy](https://cloud.githubusercontent.com/assets/7642305/9297228/080d19b0-44f0-11e5-80cc-f73217eb09e3.jpg)

In order to work around it with DirSync, Visual Studo and Powershell ISE we have had to add the following lines to the .config file(s) for the relevant .NET application and then it works.

![dirtyhack](https://cloud.githubusercontent.com/assets/7642305/9297230/160da426-44f0-11e5-9738-87828f6588ca.jpg)

Bug can be closed as its site specific. With the workaround in place we can finally access the Azure automation scripts for the subscription.

Thanks,

MD

**Comment by eamonoreilly** [comment]
Thanks Matt. Hopefully this will help others that might run into the issue also. Closing this one out. Please me know if you run into other issues or overall feedback on the ISE add on so we can make it meet your needs.
Eamon
