### ISSUE TITLE
[0.2.2.4] JSON config files and side-by-side installation of multiple versions

### ISSUE THREAD

**Issue by alexandair** [azureautomation/azure-automation-ise-addon#66]
Installing module from PowerShell Gallery using PowerShellGet supports side-by-side installation of multiple versions. JSON config files are in a module version subfolder. That's not good place for them, because we need to manually move/copy them to the folder with updated module version or we will start with blank config JSON files

**Comment by JAL9302** [comment]
This should be fixed now. Config file is in user's profile folder now.
