### ISSUE TITLE
Side-by-side installation of multiple versions requires re-run of Install-AzureAutomationIseAddOn

### ISSUE THREAD

**Issue by alexandair** [azureautomation/azure-automation-ise-addon#67]
Installing module from PowerShell Gallery using PowerShellGet supports side-by-side installation of multiple versions.
That means that we need to run Install-AzureAutomationIseAddOn every time when we update the module, to update the path in ISE profile script. That doesn't look like an optimal solution.

**Comment by alexandair** [comment]
Actually, situation is more complex. Let's say that I have version 0.2.2.4 installed. I will have the following block of code in my ISE profile:

```
# Start AzureAutomationISEAddOn snippet
if($PSIse) {
        Add-Type -Path 'C:\Users\USERNAME\Documents\WindowsPowerShell\Modules\AzureAutomationAuthoringToolkit\0.2.2.4\ISEaddon\AutomationISE.dll' | Out-Null
        $PSIse.CurrentPowerShellTab.VerticalAddOnTools.Add('Azure Automation ISE add-on', [AutomationISE.AutomationISEControl], $True) | Out-Null
}
# End AzureAutomationISEAddOn snippet
```

If I update the module to 0.2.2.5, I will need to re-run Install-AzureAutomationIseAddOn to add the proper AzureAutomationISEAddOn snippet to ISE profile file, but that won't remove the old one. I will end with two snippets--the first one points to old path and ISE will never load the new version (and I will get an error that add-on is already loaded).

**Comment by JAL9302** [comment]
This should be fixed now.
