### ISSUE TITLE
Upload draft is using static resource location

### ISSUE THREAD

**Issue by bgelens** [azureautomation/azure-automation-ise-addon#7]
Trying to publish new draft version but resource location differs so an exception is thrown.

![draft](https://cloud.githubusercontent.com/assets/10071039/9129283/0aafc82e-3cd6-11e5-968b-c0a7c88b2cbd.png)

**Comment by bgelens** [comment]
I checked the code and see it's hardcoded for now.
![hardcode](https://cloud.githubusercontent.com/assets/10071039/9129342/b74f4578-3cd6-11e5-9562-b2dbe2e45562.png)

**Comment by alstab** [comment]
that one's on me, ben. another one of the prototype hacks we are trying to clean up this week. I'll get to it soon!

**Comment by alstab** [comment]
Ben, this is fixed with my latest commit

**Comment by bgelens** [comment]
Compiled and verified!
