### ISSUE TITLE
Changing ISE profile

### ISSUE THREAD

**Issue by stefanstranger** [azureautomation/azure-automation-ise-addon#70]
Currently the AzureAutomationISEAddOn is automatically loaded when opening the ISE because the $profile.CurrentUserCurrentHost profile is being updated after installing the add-on.

I would rather decide myself if I want this loaded or not.

I changed my profile in the following:
# Start AzureAutomationISEAddOn snippet

Function Start-AzureAutomationISEAddon {

```
if($PSIse) {
        Add-Type -Path 'C:\Program Files\WindowsPowerShell\Modules\AzureAutomationAuthoringToolkit\0.2.2.4\ISEaddon\AutomationISE.dll' | Out-Null
        $PSIse.CurrentPowerShellTab.VerticalAddOnTools.Add('Azure Automation ISE add-on', [AutomationISE.AutomationISEControl], $True) | Out-Null
}
```

}

New-Alias -name AA -Value Start-AzureAutomationISEAddon
# End AzureAutomationISEAddOn snippet

This way I can just load the add-on using an alias when I want to do some AA stuff.

**Comment by JAL9302** [comment]
Please see the updated readme -- you can now choose to load the ise add on yourself in the ps ise, or have it loaded automatically each time the ps ise opens.
