### ISSUE TITLE
Azure with O365 Organizational Login Doesn't work, directs to MS Internal Azure Portal

### ISSUE THREAD

**Issue by JustinGrote** [azureautomation/azure-automation-ise-addon#73]
Hi,

 I have an Azure under an O365 organizational account and when I do the sign-in on the configuration tab it goes through and allows me to choose my org account and log in, but the configuration tab does not show my Automation Accounts. When I click Portal, it takes me to ms.portal.azure.com instead of portal.azure.com, and my username shows as "<MyName> Default Directory" in the upper right and there are none of my resources in the portal. It looks like even though I chose my organizational account, it's trying to access it as if I was an MS employee.

Using 0.2.2.6 from PSGallery. Fixed in source version maybe?

Thanks.

**Comment by alstab** [comment]
Hi Justin, thanks for testing out the add-on. Sounds like we're using the wrong link in the portal button, we'll get that fixed.

If you log in to portal.azure.com (not from the ISE), using that O365 account, do you see any resources in the portal? Are you able to create Automation Accounts?

**Comment by JustinGrote** [comment]
Yes that works just fine and I have AA deployed along with Hybrid Runbook workers to a few sites. Thanks for the add-on, it's a great idea!

**Comment by alstab** [comment]
Glad you like it! Thanks for the response, we'll look into it. adding @eamonoreilly for FYI

**Comment by eamonoreilly** [comment]
Hi Justin,
I believe authentication issues should be resolved as well as correct link to the Azure portal. Please reopen if this issue still exists.
Thanks,
Eamon

**Comment by JustinGrote** [comment]
Yep it worked for me as of that latest build. Thanks!
