### ISSUE TITLE
ISE Add-on Session Expires when left open 

### ISSUE THREAD

**Issue by elcooper** [azureautomation/azure-automation-ise-addon#74]
ISE Add-on session expires when left open.  Repo steps:
1.  Log into ISE Add-on with personal account
2.  Log into other sessions with Msft creds
3.  Leave ISE open for evening
4. Signon window pops up and cannot be escaped

Screenshot below

![ise add-on error](https://cloud.githubusercontent.com/assets/10818658/10699444/a4d359a8-796b-11e5-8c04-41d71bdb8421.png)

**Comment by eamonoreilly** [comment]
Checked in a fix to try and refresh the user that signed into the ISE and also to only show one login window if authentication is actually required.
