### ISSUE TITLE
Bug during install "could not find file" AzureAutomationAuthoringToolkitConfig.json

### ISSUE THREAD

**Issue by pcgeek86** [azureautomation/azure-automation-ise-addon#77]
Windows 10 Build 10240

<img width="841" alt="screen shot 2015-11-03 at 2 06 10 pm" src="https://cloud.githubusercontent.com/assets/466713/10923172/453ada62-8234-11e5-8645-337f6033a36a.png">

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by JAL9302** [comment]
Does that file exist?

On Tue, Nov 3, 2015 at 2:11 PM, Trevor Sullivan notifications@github.com
wrote:

> Windows 10 Build 10240
> 
> [image: screen shot 2015-11-03 at 2 06 10 pm]
> https://cloud.githubusercontent.com/assets/466713/10923172/453ada62-8234-11e5-8645-337f6033a36a.png
> 
> Cheers,
> Trevor Sullivan
> Microsoft MVP: PowerShell
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/azureautomation/azure-automation-ise-addon/issues/77.

## 

_Joe Levy_
Duke University '12, Computer Science
www.jodoglevy.com
919.886.6563

**Comment by pcgeek86** [comment]
Yes it does.

**Comment by JAL9302** [comment]
Do you get this error every time you open the ISE now? Does the ISE add on load?

**Comment by pcgeek86** [comment]
It works properly now. It only happened the first time.

**Comment by eamonoreilly** [comment]
Closing for now as we have not had any more reports of this with the latest download. Will reopen if the issue comes up again.
