### ISSUE TITLE
Unable to load solution in VS since last commit

### ISSUE THREAD

**Issue by bgelens** [azureautomation/azure-automation-ise-addon#8]
C:\GIT\azure-automation-ise-addon\AutomationISE\AutomationISE.csproj : error  : The project file could not be loaded. Name cannot begin with the '<' character, hexadecimal value 0x3C. Line 129, position 2.  C:\GIT\azure-automation-ise-addon\AutomationISE\AutomationISE.csproj

**Comment by eamonoreilly** [comment]
Hi Ben, can you sync the latest file again? I had a merge conflict I had to clean up.
Thanks,
Eamon

**Comment by bgelens** [comment]
Hi Eamon, that fixed it thanks! Ben
