### ISSUE TITLE
If there is a new runbook which is never published to Azure, then gray out the Test Draft button

### ISSUE THREAD

**Issue by anirudhgarg** [azureautomation/azure-automation-ise-addon#82]
Currently it is not grayed and we get an Error Message which says: "Cannot connect to Azure"

**Comment by alstab** [comment]
Anirudh, I don't see this behavior. Are you sure you were using the latest version of the add-on?

**Comment by anirudhgarg** [comment]
Yes this must be because I am using an older version, you can resolve this
as non repro.
