### ISSUE TITLE
Add Support for Certificate Assets

### ISSUE THREAD

**Issue by alstab** [azureautomation/azure-automation-ise-addon#83]
The add-on currently does not support retrieving certificates with Get-AutomationCertificate. This will become a problem as users start to use service principals + certificates for authentication to ARM in their runbooks.

**Comment by JAL9302** [comment]
Don't the Azure cmdlets take in a cert thumbprint, not a cert directly?

**Comment by alstab** [comment]
Yes, but until we install the user's certs in the right place, you have to pull the cert asset and install it and then call the Azure cmdlets. So at the moment, parity between Automation environment and local environment is broken.

If (hopefully when) we make the change to load the user's certs to the right place, this issue won't really be a problem. Just want to track it for now in case something goes wrong with the cert loading.

**Comment by JAL9302** [comment]
But locally, we can just instruct user to put the cert in the correct place. In fact, they'd probably have to have it in that location regardless of testing Azure Automation runbooks, to use cert for service principal auth locally.

Assuming user's cert is in the right cert store locally, this move cert code wouldn't be needed locally. So can we just add a condition to the top of that move cert code that checks if cert is in right location already? This way Get-AutomationCertificate isn't needed when that same runbook runs locally.

**Comment by alstab** [comment]
Yes, the user has to put the cert in the right place regardless.

The problem is, right now, to do that check without calling Get-AutomationCertificate, you need to have a variable asset containing the certificate's thumbprint. So there are two assets representing the same thing. We'll push for the fixed cert loading in AA so this won't be necessary.

**Comment by eamonoreilly** [comment]
Certificate management is now available.
