### ISSUE TITLE
Test Runbook on Hybrid Runbook Worke

### ISSUE THREAD

**Issue by mattmcnabb** [azureautomation/azure-automation-ise-addon#84]
When I open the test pane to test a runbook sometimes I am presented with the option to run this in 
Azure or on a runbook worker. Other times I am not presented with this option. Is this a bug or are there some situations where this option is not offered? If so, when can I run it on a worker and when can I only run it in Azure?

Thanks!

**Comment by eamonoreilly** [comment]
Hi Matt,
If you have a hybrid worker registered in your automation account, then you should always be presented with the option to run on the hybrid worker or in Azure when testing the draft in Azure. Are you seeing scenarios where the option is not available for the same or different runbooks within the automation account?
Thanks,
Eamon

**Comment by mattmcnabb** [comment]
Yes, that is what I'm seeing. So far I haven't been able to figure out what sequence of events leads to it not showing up.

**Comment by eamonoreilly** [comment]
Hi Matt,
I'm closing this one for now but please let me know if you see this again and we can have another look. I have not been able to reproduce this behavior.
Thanks
Eamon

**Comment by mattmcnabb** [comment]
Eamon,

Sorry I left this one hanging out there. The issue seemed to be resolved after I updated to the 2.3.1 release from the PSGallery.

Thanks!
