### ISSUE TITLE
Unable to select subscription with O365 Organizational Login, autoselects first subscription and grays out the login box

### ISSUE THREAD

**Issue by JustinGrote** [azureautomation/azure-automation-ise-addon#87]
Hi guys,

Slightly odd issue, when attempting to log in with an O365 Organization login. I have multiple subscriptions but it autoselects the first subscription and box is grayed out, so I cannot select my MS Partner Subscription where my automation account.
![image](https://cloud.githubusercontent.com/assets/15258962/11280086/e8612702-8ea8-11e5-9faa-da4a098d02f3.png)

I tested with a different organizational account in another tenant and it worked fine and showed the multiple subscriptions and was able to toggle. One difference between the two is this is an ADFS integrated login whereas the non-functional login is AADConnect sync only. I'm fairly sure that's not related but it's worth bringing up.

Here's the fiddler XML output for the subscription query if there's any flags or anything which might be contributing to this behavior (unique details redacted)

```
<?xml version="1.0" encoding="UTF-8"?>
<Subscriptions xmlns="http://schemas.microsoft.com/windowsazure" xmlns:i="http://www.w3.org/2001/XMLSchema-instance">
   <Subscription>
      <SubscriptionID>XXXXXXXXXXXXXXX</SubscriptionID>
      <SubscriptionName>Access to Azure Active Directory</SubscriptionName>
      <SubscriptionStatus>Active</SubscriptionStatus>
      <AccountAdminLiveEmailId>JGrote@XXXXXXXXXXXXXXX.net</AccountAdminLiveEmailId>
      <ServiceAdminLiveEmailId>jgrote@XXXXXXXXXXXXXXX.net</ServiceAdminLiveEmailId>
      <MaxCoreCount>20</MaxCoreCount>
      <MaxStorageAccounts>100</MaxStorageAccounts>
      <MaxHostedServices>20</MaxHostedServices>
      <CurrentCoreCount>0</CurrentCoreCount>
      <CurrentHostedServices>0</CurrentHostedServices>
      <CurrentStorageAccounts>0</CurrentStorageAccounts>
      <MaxVirtualNetworkSites>50</MaxVirtualNetworkSites>
      <MaxLocalNetworkSites>20</MaxLocalNetworkSites>
      <MaxDnsServers>20</MaxDnsServers>
      <OfferCategories>Azure_Platform_All;Azure_Direct;Azure_Paid;Azure_Hidden;Azure_Consumption;Azure_MS-AZR-0110P;Azure_AAD;Individual</OfferCategories>
      <MaxExtraVIPCount>-1</MaxExtraVIPCount>
      <AADTenantID>XXXXXXXXXXXXXXX</AADTenantID>
      <CreatedTime>2015-07-27T19:26:34Z</CreatedTime>
   </Subscription>
   <Subscription>
      <SubscriptionID>XXXXXXXXXXXXXXX</SubscriptionID>
      <SubscriptionName>Microsoft Partner Network</SubscriptionName>
      <SubscriptionStatus>Active</SubscriptionStatus>
      <AccountAdminLiveEmailId>JGrote@XXXXXXXXXXXXXXX.net</AccountAdminLiveEmailId>
      <ServiceAdminLiveEmailId>o365admin@XXXXXXXXXXXXXXX.onmicrosoft.com</ServiceAdminLiveEmailId>
      <MaxCoreCount>20</MaxCoreCount>
      <MaxStorageAccounts>100</MaxStorageAccounts>
      <MaxHostedServices>20</MaxHostedServices>
      <CurrentCoreCount>1</CurrentCoreCount>
      <CurrentHostedServices>1</CurrentHostedServices>
      <CurrentStorageAccounts>1</CurrentStorageAccounts>
      <MaxVirtualNetworkSites>50</MaxVirtualNetworkSites>
      <MaxLocalNetworkSites>20</MaxLocalNetworkSites>
      <MaxDnsServers>20</MaxDnsServers>
      <OfferCategories>Azure_Platform_All;Azure_Paid;Azure_Consumption;Azure_MSPP;Azure_Credit;Azure_MS-AZR-0025P;Individual</OfferCategories>
      <MaxExtraVIPCount>-1</MaxExtraVIPCount>
      <AADTenantID>XXXXXXXXXXXXXXX</AADTenantID>
      <CreatedTime>2015-07-27T22:54:39Z</CreatedTime>
   </Subscription>
   <Subscription>
      <SubscriptionID>XXXXXXXXXXXXXXX</SubscriptionID>
      <SubscriptionName>Pay-As-You-Go</SubscriptionName>
      <SubscriptionStatus>Disabled</SubscriptionStatus>
      <AccountAdminLiveEmailId>JGrote@XXXXXXXXXXXXXXX.net</AccountAdminLiveEmailId>
      <ServiceAdminLiveEmailId>JGrote@XXXXXXXXXXXXXXX.net</ServiceAdminLiveEmailId>
      <MaxCoreCount>20</MaxCoreCount>
      <MaxStorageAccounts>100</MaxStorageAccounts>
      <MaxHostedServices>20</MaxHostedServices>
      <CurrentCoreCount>0</CurrentCoreCount>
      <CurrentHostedServices>0</CurrentHostedServices>
      <CurrentStorageAccounts>0</CurrentStorageAccounts>
      <MaxVirtualNetworkSites>50</MaxVirtualNetworkSites>
      <MaxLocalNetworkSites>20</MaxLocalNetworkSites>
      <MaxDnsServers>20</MaxDnsServers>
      <OfferCategories>Azure_Platform_All;Azure_Direct;Azure_Paid;Azure_Consumption;Azure_MS-AZR-0003P;Individual</OfferCategories>
      <MaxExtraVIPCount>-1</MaxExtraVIPCount>
      <AADTenantID>XXXXXXXXXXXXXXX</AADTenantID>
      <CreatedTime>2015-08-21T17:12:00Z</CreatedTime>
   </Subscription>
</Subscriptions>
```

Thanks.

**Comment by JustinGrote** [comment]
One other thing I can think of is that this account has both a Microsoft account and Organizational account on the same email address, while the working one is org only. I was sure to ensure I was logging in with my organizational account and not the Microsoft account, but maybe the subscription check step doesn't distinguish.

**Comment by alstab** [comment]
Hi Justin, I think I actually came across this problem myself recently and fixed it. I'll get you a build with the changes and we can see if it works for you. Quick question -- does the subscription that it autoselects have any automation accounts? If it does, does the add-on download them correctly?

**Comment by JustinGrote** [comment]
I can check it out from a branch in Git if you define to test.

The subscription is just the first in the list (azure active directory) and does not have any automation accounts. The one I want is the second in the list of the XML response (Microsoft Partner Network)

**Comment by alstab** [comment]
Cool, that would be helpful. Just get the latest code in master and it should be fixed (master is currently somewhat ahead of 0.2.2.9, the most recent release on PS Gallery).

**Comment by JustinGrote** [comment]
Err don't have VS set up on my current test machine, my bad. No biggie,
I'll check it at next build. Thanks for the fast response and resolution!

**Comment by alstab** [comment]
No problem Justin, I hope this works! Try the latest build on PS Gallery (0.2.3): https://www.powershellgallery.com/packages/AzureAutomationAuthoringToolkit/

**Comment by JustinGrote** [comment]
Fixed it. Thanks!

**Comment by alstab** [comment]
Great to hear, thanks for letting us know!
