### ISSUE TITLE
Create New runbook results in file-in-use error displayed

### ISSUE THREAD

**Issue by NoahStahl** [azureautomation/azure-automation-ise-addon#88]
When creating a new local runbook, an error dialog is shown immediately upon completing the dialog for a new script runbook: "The runbook could not be opened...because it is being used by another process." Despite the error message, the runbook file is created successfully and can be worked with after dismissing the error. This is on Windows 10 1511.

One guess is the File.Create in AutomationRunbookManager.cs line 288 needs to closed before returning? http://stackoverflow.com/questions/4680284/system-io-file-create-locking-a-file

![ise-file-in-use](https://cloud.githubusercontent.com/assets/7528994/11918777/31eecf42-a70d-11e5-918e-3e1150d80864.png)

**Comment by eamonoreilly** [comment]
Thanks Noah. Implemented the suggested fix by you to cover this case.
