### ISSUE TITLE
Account doesn't stay signed in

### ISSUE THREAD

**Issue by NoahStahl** [azureautomation/azure-automation-ise-addon#89]
Not sure if this is expected behavior, but even when selecting "Keep me signed in" when authenticating, after closing/opening again I'm forced to re-enter credentials. It would be nice to have the ISE persist a login across sessions or at least respect the sign-in dialog option.

**Comment by alstab** [comment]
@eamonoreilly may want to have a look at this, since he worked most on the auth code

**Comment by eamonoreilly** [comment]
This is possible Noah but I would need to introduce a sign out button also to allow users to switch between Microsoft and organization accounts. I'll have a look when I get some time. Thanks for the feedback.
Eamon

**Comment by eamonoreilly** [comment]
#142 I have added this to the latest code Noah. It should show up on the next release to the gallery or you can build from source to see it.
Thanks,
Eamon
