### ISSUE TITLE
Clicking the "Open" button restarts Windows Explorer

### ISSUE THREAD

**Issue by pcgeek86** [azureautomation/azure-automation-ise-addon#99]
The **Open** button on the **Configuration** page of the Azure Automation ISE add-on should open a Windows Explorer window, pointing to the path specified under `Account Content Location`. Instead, what happens on a Windows 10 RTM client, is that Windows Explorer crashes or closes, and re-opens. The taskbar disappears and reappears, and no file explorer window is ever shown.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by eamonoreilly** [comment]
Hi Trevor, I'm not able to reproduce this on my Windows 10 box. Is there anything unique about the location and does it reproduce every time?
Thanks,
Eamon

**Comment by pcgeek86** [comment]
@eamonoreilly I just tried to repro it again, and it's not happening.
